# terraform plan workflow example
name: Plan
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      tfvars:
        required: false
        type: string
      backend_config:
        required: false
        type: string
    outputs:
      environment:
        description: 'The target environment for the plan'
        value: ${{ inputs.environment }}
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Terraform Plan
        id: plan
        run: |
          echo "Planning Terraform..."
          echo "Environment: ${{ inputs.environment }}" 